<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>code.log</string>
        <key>fileTypes</key>
        <array>
            <string>log</string>
        </array>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>
            <dict>
                <!-- Exception (with custom naming and namespacing) -->
                <key>match</key>
                <string>\b(?i:((\.)*[a-z]|[0-9])*(Exception|Error|Failure|Fail))\b</string>
                <key>name</key>
                <string>invalid</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(Down|Error|Failure|Fail|Fatal|ERR|Failed|failed))(\:|\b)</string>
                <key>name</key>
                <string>invalid.illegal</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(hint|info|information))(\:|\b)</string>
                <key>name</key>
                <string>keyword</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(warning|warn|test|debug|undefined|NaN))(\:|\b)</string>
                <key>name</key>
                <string>string.quoted</string>
                <!-- <string>invalid.deprecated</string> -->
            </dict>
            <dict>
                <!-- output from (npm install) log -->
                <key>match</key>
                <string>(-)+>|├(─)+|└(─)+</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
        </array>
    </dict>
</plist>