{
 "title": "webOS dashboard",
 "description": "InfluxDB dashboards for webOS OSE metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "processname",
    "label": "ProcessName",
    "query": "select DISTINCT(\"processName\") from (select \"processName\",\"smaps_PSS\" from \"processMonitoring\" WHERE host =~ /$server/ AND $timeFilter)"
   },
   {
    "name": "pid",
    "label": "PID",
    "query": "SHOW TAG VALUES FROM \"processMonitoring\" WITH KEY = \"pid\" WHERE host =~ /$server/ AND processName =~ /$processname/"
   },
   {
    "name": "processfrompid",
    "query": "SHOW TAG VALUES FROM \"processMonitoring\" WITH KEY = \"processName\" WHERE host =~ /$server/ AND pid =~ /$pid/"
   }
  ]
 },
 "panels": [
  {
   "title": "webProcessSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "$tag_webId-$tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "webId" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "webProcessSize",
     "query": "SELECT mean(\"webProcessSize\") FROM \"webProcessSize\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"webId\", \"pid\" fill(linear)",
     "select": [
      [
       { "params": [ "webProcessSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "procstat",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "query": "SELECT last(\"cpu_usage\") AS \"cpu_usage\", last(\"memory_usage\") AS \"memory_usage\", last(\"memory_rss\") AS \"memory_rss\", last(\"memory_vms\") AS \"memory_vms\", last(\"memory_swap\") AS \"memory_swap\", last(\"cpu_time_user\") AS \"cpu_time_user\",  last(\"memory_rss\") +  last(\"memory_vms\") AS \"test\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"pid\" =~ /^$pid$/) AND $timeFilter GROUP BY \"pid\"",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cpu_usage" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memory_usage" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memory_rss" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_vms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memory_vms" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_swap" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memory_swap" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_time_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cpu_time_user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Total (RSS + swap) from procstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT mean(\"memory_rss\") FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"pid\" =~ /^$pid$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(linear)",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Total (PSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "$tag_processName-$tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "processName" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "processMonitoring",
     "select": [
      [
       { "params": [ "smaps_PSS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "processName", "operator": "=~", "value": "/^$processfrompid$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage(%) per interval",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "repeat": "processfrompid",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_processName-$tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "processName" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "processMonitoring",
     "select": [
      [
       { "params": [ "interval_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "processName", "operator": "=~", "value": "/^$processfrompid$/" }
     ]
    }
   ]
  },
  {
   "title": "$processfrompid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "repeat": "processfrompid",
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "processName" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "processMonitoring",
     "select": [
      [
       { "params": [ "vmRSS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "vmRSS" ], "type": "alias" }
      ],
      [
       { "params": [ "smaps_RSS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "RSS" ], "type": "alias" }
      ],
      [
       { "params": [ "smaps_USS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "USS" ], "type": "alias" }
      ],
      [
       { "params": [ "smaps_PSS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PSS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "processName", "operator": "=~", "value": "/^$processfrompid$/" }
     ]
    }
   ]
  }
 ]
}